scitq:
  port: 50051
  log_level: "info"
  worker_token: "changeMeIamUnsecure123"
  jwt_secret: "weAreOnAMissionFromGod"
  certificate_key: "/home/ubuntu/scitq2/certs/privkey.pem"
  certificate_pem: "/home/ubuntu/scitq2/certs/fullchain.pem"
providers:
  azure:
    primary:
      default_region: swedencentral
      subscription_id: XXXXXX
      client_id: XXXXX
      client_secret: XXXXX
      tenant_id: XXXXX
      update_periodicity: 10m
      image:
        publisher: "Canonical"
        offer: "ubuntu-24_04-lts"
        sku: "server"
        version: "latest"
      quotas:
        swedencentral:
          cpu: 320
  openstack:
    ovh:
      auth_url: "https://ovh.example.com:5000/v3"
      username: "ovhuser"
      password: "ovhpass"
      domain_name: "default"
      tenant_name: "ovh-project"
      region: "RegionOne"
      image_id: "img-ovh"
      flavor_id: "flavor-ovh"
      network_id: "net-ovh"
      custom:
        quota_endpoint: "https://ovh.example.com/api/quotas"
        pricing_endpoint: "https://ovh.example.com/api/pricing"
    standard:
      auth_url: "https://openstack.example.com:5000/v3"
      username: "stduser"
      password: "stdpass"
      domain_name: "default"
      tenant_name: "std-project"
      region: "RegionTwo"
      image_id: "img-std"
      flavor_id: "flavor-std"
      network_id: "net-std"
      custom: {}
