[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = { workspace = true }
prost = "0.13"

[build-dependencies]
tonic-build = "0.12"

[lib]
name = "common" # Name of your library crate
path = "src/lib.rs"        # Path to your library file
