# .github/workflows/build.yml
name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Prepare Python package for DSL
        run: make add-py-version

      - name: Verify Docker availability
        run: docker version

      - name: Pre-pull base Docker images
        run: |
          docker pull postgres:17-alpine

      - name: Build Go project
        run: go build ./...

      - name: Run Go tests
        run: go test -v ./tests/integration